# Your personal GitHub token
github_token: de4893e9f9b95cc24d7403abee0f403496343712
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: shop

# Virtual machine IP
ip: 192.168.33.137

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 512
